### ISSUE TITLE
Fix failing tests.

### ISSUE THREAD

**Issue by PaliwalArpit** [onekiloparsec/aa-js#13]
@onekiloparsec As mentioned creating a new issue for fixing tests. Please accept if this is fine with you.

**Comment by onekiloparsec** [comment]
All tests pass locally for me. Let see with Travis.

**Comment by onekiloparsec** [comment]
Damn, Date inside tests were wrong. Thanks for pushing the subject. It is now fixed, and Travis validates it green! 🍾
