### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by called2voyage** [onekiloparsec/aa-js#20]
Did you have a particular license in mind when making this work available? Would you mind adding one to help ensure the future availability of these tools? I recommend GPL v3. It's what I use myself.

**Comment by onekiloparsec** [comment]
Sure, it's something missing. I tend to use the MIT one.

**Comment by called2voyage** [comment]
MIT makes sense. Thanks!

**Comment by onekiloparsec** [comment]
Done. 703cd68f2f2b12956b871f02c8942fe2377308f7
