### ISSUE TITLE
Introduce Mars details and coordinates

### ISSUE THREAD

**Issue by danieledep** [onekiloparsec/aa-js#21]
Hi I'm trying to see if I can use this library, I tried your basic example:
```
import { julianday, moon } from 'astronomical-algorithms'

...

const jd = julianday.getJulianDay(new Date()),
const coords = moon.equatorialCoordinates(jd)

```
but at compile I get this error:
```
"export 'julianday' was not found in 'astronomical-algorithms'
```
I know it's still a wip, I'm just trying to understand if i'm making mistakes on my side, thanks

**Comment by onekiloparsec** [comment]
Sorry the README is misleading. I am still not entirely convinced of the export method I've chosen, but since you've closed the issue, I guess you found your way. 

The standard way of importing is now:

```
import aa from 'astronomical-algorithms'
const jd = aa.julianday.getJulianDay(new Date()),
const coords = aa.moon.equatorialCoordinates(jd)
```

**Comment by danieledep** [comment]
Yes the one you wrote could be a solution, i made it working also with something like this
```
import * as aa from 'astronomical-algorithms'
import { julianday } from 'astronomical-algorithms/dist/julianday.js'
```
btw, as a offtopic question.. will you add other solar planets? because I was interested in mars coordinates.

**Comment by onekiloparsec** [comment]
> btw, as a offtopic question.. will you add other solar planets? because I was interested in mars coordinates.

:-) Me too. It's always a matter of priorities. But okay, I'll put Mars on top.

**Comment by danieledep** [comment]
Ah ok! keep up the good work then :)

**Comment by onekiloparsec** [comment]
I just published version 1.1(.1) with some basics of Mars. But it is UNTESTED for now.

Be careful too: I've normalized the order of parameters of some functions (lat/lng).

**Comment by danieledep** [comment]
i tried it out, looks cool!

**Comment by onekiloparsec** [comment]
Hi. Mars details were wrong, even if coordinates were correct. This is now updated on `HEAD` with a unit test. Working on Jupiter right now, and others will follow.
