### ISSUE TITLE
How to get geocentric coords of a planet?

### ISSUE THREAD

**Issue by HandsomeOne** [onekiloparsec/aa-js#41]
Expected `<Planet>.getApparentEquatorialCoordinates` was **geocentric**, but it seems to remain **heliocentric**, how could I get geocentric coords of a planet?

Related: https://github.com/onekiloparsec/SwiftAA/issues/24

**Comment by onekiloparsec** [comment]
Hey. Sorry, I see your question so late! 

You are totally right, the `getApparentEquatorialCoordinates` are still heliocentric, and it is a problem. I am actually working on it to fix that.

And I think I will also include the topocentric version of it, to be complete!

**Comment by onekiloparsec** [comment]
@HandsomeOne while working on a new implementation that will answer your question more easily by far, I just recalled you have nonetheless the possibility to get the geocentric coordinates of a planet already today!

Use `<Planet>.getPlanetaryDetails(jd).apparentGeocentricEquatorialCoordinates`

The current API is ugly, but it works. In the next version, it will be simpler, and will have a lot more informatin beside these coords.

**Comment by HandsomeOne** [comment]
Thanks!

**Comment by onekiloparsec** [comment]
I just finished to rewrite entirely `aa-js` with arbitrary-precision computations, using decimal.js. The v3 has some breaking changes but it will be a lot better. 

I need to take some rest, add more tests before releasing v3. But you can already have a look if you point to `HEAD`.
