### ISSUE TITLE
MapTo0To360Range causing loss of precision

### ISSUE THREAD

**Issue by PabloDons** [onekiloparsec/aa-js#45]
Thank you for this awesome library! I use it to make an app that calculates precise age.

However I noticed that precision wasn't great. Specifically because of the function `MapTo0To360Range`, so I removed it in a local version. This also made my code simpler because I was reimplementing the lost information anyway (number of orbital cycles between dates).

Could This be removed and have this function be available to be used independently by developers? This is a breaking change so I suggest a whole new function, but without `MapTo0To360Range`, while the current function would become a wrapper.

I can make a PR if this sounds good!

**Comment by onekiloparsec** [comment]
Hey. Thanks for your question/remark. I agree with you, this is an ugly function that comes from the migration from SwiftAA, my Swift version of Astronomical Algorithms.

If you have a PR, I'll be happy to review it. I am currently working an `aa-js` to correct an important thing about Planet coordinates (so called "apparent" coordinates are not taking into account the light time travel). So to say, I will include your feedback in the next release anyway.

But I would be happy to know a bit more about your use case, and where this function really impacts the precision (of the age of what?)

**Comment by PabloDons** [comment]
> But I would be happy to know a bit more about your use case, and where this function really impacts the precision (of the age of what?)

I calculate number of earth years since birthday with the progress in a year being equal to the progress of earth around the sun. I display it with a precision of 9 decimals. That's a precision of 0.03 seconds. However I was only getting a precision of around 0.4 seconds. That limits the update frequency to 3hz, whereas I was trying to get 60hz. (0.016 seconds).

I saw in the code that if I just juggle the calculations a bit, It's possible to get higher precision (division by 1e8 AFTER the modulus operation), but I just wanted to get rid of the function frankly :P

> If you have a PR, I'll be happy to review it.

Then I'll get to work!

**Comment by onekiloparsec** [comment]
Interesting! Thanks to your issue, and the other one #41 I am currently reviewing and updating all the Planets APIs, to make it more consistent and easier to use. While doing so, I changed the precision of the function from 8 to 20, and my tests pass with more precision.

I agree with the author of the implementation that in some cases, the function is not really precise beyond the 8th decimal. But if my `aa-js` tests pass with more precision, I see no reason to not increase it.

The new implementation will take some time (~a few days). If that's OK for you to wait for the new release, I'll focus on that (instead of doing an intermediate bugfix release).

**Comment by onekiloparsec** [comment]
I found a much better solution. I couldn't believe I didn't know about [decimal.js](https://github.com/MikeMcl/decimal.js/). 

Since it is too good to be true, I will adopt `decimal.js` for the rest of calculations too...

**Comment by onekiloparsec** [comment]
`aa-js` has been completely rewritten with Decimal.js. The CI is green. I need to get some rest, add more tests, and I'll release v3. But you can already check it if you point to the `HEAD`.

**Comment by PabloDons** [comment]
Thank you so much! This is fantastic!

The original original premise of this issue is pretty much resolved, but there's one more thing I'd like to ask for:

> However I noticed that precision wasn't great. Specifically because of the function MapTo0To360Range, so I removed it in a local version. This also made my code simpler because I was reimplementing the lost information anyway (number of orbital cycles between dates).

I would like to get the number of orbital cycles between two dates. Basically just the same function but without the modulus operation. Should I make a separate issue for this?

**Comment by onekiloparsec** [comment]
Sure, of course. But, what function exactly? 

You need only Earth or you want also the other planets?

**Comment by PabloDons** [comment]
EclipticLongtitude, i only want earth 😄

**Comment by onekiloparsec** [comment]
Sorry, but I still try to understand how to give you the value you are looking for, without making tricky stuff inside the lib.

Semantically speaking, the value of the ecliptic longitude expressed in degrees is necessarily comprised between 0º and 360º. Hence, I do not want to remove the `fmod` function.

As far as I understand, you compare two ecliptic longitudes computed at two different times to get... an age? Why don't you use 360º for complete cycles/years for instance ?

**Comment by PabloDons** [comment]
Well, semantically what I'm looking for is a "rotation amount". How many degrees of longitude "change" between two dates. That's fundamentally different from a longitudinal coordinate, but is calculated the same (and is not a constrained range like coordinates are). Does that make more sense?

An example function definition:
```javascript
function getEclipticOrbitAmount(jdStart, jdEnd)
```

**Comment by PabloDons** [comment]
This is what I'm asking for:

```javascript
function getEclipticLongitude(jd) {
  return fmod360(_getEclipticLongitudeUnclamped(jd));
}

function getEclipticOrbitAmount(jdStart, jdEnd) {
  return _getEclipticLongitudeUnclamped(jdEnd) - _getEclipticLongitudeUnclamped(jdStart);
}
```

**Comment by onekiloparsec** [comment]
Got it. Will do.

**Comment by onekiloparsec** [comment]
Would `function getEclipticLongitudeRange(jdStart, jdEnd)` make sense? I am not sure whether "orbit amount" is holding more sense, or is more precise. But you have more context, hence I prefer to ask. My proposition is simply descriptive, and doesn't explain much.

**Comment by PabloDons** [comment]
I don't know if I do have more context, but personally I'd say that "range" is the wrong word to use here. "Rotation" is more accurate and is an amount in mathematics like I am describing. Maybe `function getEclipticLongitudinalRotation(jdStart, jdEnd)` is better?

**Comment by onekiloparsec** [comment]
Sold. 

I've improved a lot the tests and checks today (fixing quite a few problems...). I am getting closer to v3 release (probably tomorrow).

**Comment by PabloDons** [comment]
You're amazing!

**Comment by onekiloparsec** [comment]
Thanks. :-) Actually, the timing was good for me too. This new version is critical for the very near future of my platform https://www.arcsecond.io

**Comment by onekiloparsec** [comment]
Damn, I hate the publication process with npm. It never works out of the box. Anyway, v3 is now available (v3.0.1 in npmjs.org...).

You can now use `Earth.getEclipticLongitudinalRotation(jdStart, jdEnd)`

**Comment by PabloDons** [comment]
And it's working like a beauty! Thanks!

**Comment by onekiloparsec** [comment]
The rewrite of `aa-js` with `decimal.js` has a huge impact on performance. I need both modes... I will re-introduce less accurate computations as an opt-in. No changes for you, default will remain `highPrecision` everywhere I introduce it.

**Comment by onekiloparsec** [comment]
Bummer... I have too many performance issues with Decimal.js. Even with dual implementation, I get performance slowdowns with `.toNumber()` calls, despite running on the latest MacBook Pro M3.

I will keep the APIs as there are, but remove all Decimals.

**Comment by onekiloparsec** [comment]
I will try to keep precision good enough for `Earth.getEclipticLongitudinalRotation` though.
