### ISSUE TITLE
getRiseSetTransitTimes missing 'new' when converting jdValue to JulianDate

### ISSUE THREAD

**Issue by joseph-long** [onekiloparsec/aa-js#7]
```
> AA.transits.getRiseSetTransitTimes(sun.apparentEquatorialCoordinates())
Thrown:
TypeError: Cannot read property 'midnightJulianDay' of undefined
```

looks like https://github.com/onekiloparsec/AA.js/blob/master/src/transits.js#L9 should maybe be

```
var jd = (new julianday.JulianDay(jdValue)).midnightJulianDay();
```

**Comment by onekiloparsec** [comment]
Sorry for the long delay (vacations times). You are perfectly right. I am not entirely satisfied with the current APIs (method names, and consistency), but for now, I'll keep going like that.

**Comment by onekiloparsec** [comment]
v0.6.0 now available with the fix.
